### PR TITLE
Create pluggable filter

### PR DESCRIPTION
**Pull request by neekolas**
## Summary
- Necessary piece for the new XMTP filter protocol. Very similar to previous PR for creating a pluggable store
- Also makes some struct fields public so that I can reuse the structs more easily in the XMTP Filter module

### CODE REVIEW

**Review by mkobetic — APPROVED** [review]
👍 Was debating the IFilter name, but not sure there is a better choice given that Filter is used for something else.

Maybe `filter.Interface`?  I've seen  that used sometimes.

**Comment by neekolas** [comment]
I also don't love `IFilter`. Feels like an Apple product.

The hard thing about naming it `Interface` is that there is other stuff in this package that may also need an interface at some point

**Comment by neekolas** [comment]
I thought about just renaming the `Filter` to `FilterImpl` or something, so that I could use `Filter` as the name for the interface.

**Comment by mkobetic** [comment]
I think what's called `Filter` now is really a filter, I would hesitate to change that. How about `filter.Protocol` ?

**Comment by neekolas** [comment]
I'm alright with `Protocol`

**Pull request merged**
